import { describe, it, expect, beforeEach, afterEach } from "bun:test";
import * as path from "node:path";
import * as fs from "node:fs/promises";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";

// Import the write rule checker (we'll test the logic directly)
// Note: The actual function is not exported, so we'll test via file operations

type WriteMode = "rewrite" | "append" | "patch_section";

interface WriteRule {
  allowed: WriteMode[];
  blocked?: string;
}

// Copy of the getWriteRule logic for testing
function getWriteRule(relPath: string): WriteRule {
  const WRITE_RULES: Record<string, WriteRule> = {
    "hot-memory.md": { allowed: ["rewrite"] },
    "observations.md": { allowed: ["append"] },
    "action-items.md": { allowed: ["append", "patch_section"] },
    "entities.md": { allowed: ["patch_section"] },
    "calendar.md": { allowed: ["rewrite"] },
    "health.md": { allowed: ["patch_section"] },
    "habits.md": { allowed: ["patch_section"] },
    "home.md": { allowed: ["patch_section"] },
    "cog-meta/self-observations.md": { allowed: ["append"] },
    "cog-meta/patterns.md": { allowed: ["patch_section"] },
    "glacier/index.md": {
      allowed: [],
      blocked: "Auto-generated by /cog-housekeeping — do not edit manually",
    },
    "link-index.md": {
      allowed: [],
      blocked: "Auto-generated by /cog-housekeeping — do not edit manually",
    },
  };

  const filename = path.basename(relPath);
  const relNorm = relPath.replace(/\\/g, "/");

  // Blocked patterns
  if (filename === "INDEX.md") {
    return {
      allowed: [],
      blocked: "Auto-generated by /cog-housekeeping — do not edit manually",
    };
  }
  if (relNorm === "glacier/index.md" || relNorm.endsWith("/glacier/index.md")) {
    return {
      allowed: [],
      blocked: "Auto-generated by /cog-housekeeping — do not edit manually",
    };
  }
  if (relNorm === "link-index.md") {
    return {
      allowed: [],
      blocked: "Auto-generated by /cog-housekeeping — do not edit manually",
    };
  }

  // Check exact relative path match (for cog-meta files)
  if (WRITE_RULES[relNorm]) return WRITE_RULES[relNorm];

  // Check basename match (works across domains)
  if (WRITE_RULES[filename]) return WRITE_RULES[filename];

  // Default: all modes allowed
  return { allowed: ["rewrite", "append", "patch_section"] };
}

function isWriteAllowed(relPath: string, mode: WriteMode): boolean {
  const rule = getWriteRule(relPath);
  return rule.allowed.includes(mode);
}

describe("COG Memory Write Rules", () => {
  let tempDir: string;

  beforeEach(async () => {
    tempDir = await mkdtemp(path.join(tmpdir(), "cog-memory-test-"));
  });

  afterEach(async () => {
    await fs.rm(tempDir, { recursive: true, force: true });
  });

  describe("hot-memory.md", () => {
    it("allows rewrite", () => {
      expect(isWriteAllowed("personal/hot-memory.md", "rewrite")).toBe(true);
    });

    it("blocks append", () => {
      expect(isWriteAllowed("personal/hot-memory.md", "append")).toBe(false);
    });

    it("blocks patch_section", () => {
      expect(isWriteAllowed("personal/hot-memory.md", "patch_section")).toBe(false);
    });
  });

  describe("observations.md", () => {
    it("allows append", () => {
      expect(isWriteAllowed("personal/observations.md", "append")).toBe(true);
    });

    it("blocks rewrite", () => {
      expect(isWriteAllowed("personal/observations.md", "rewrite")).toBe(false);
    });

    it("blocks patch_section", () => {
      expect(isWriteAllowed("personal/observations.md", "patch_section")).toBe(false);
    });
  });

  describe("action-items.md", () => {
    it("allows append", () => {
      expect(isWriteAllowed("work/action-items.md", "append")).toBe(true);
    });

    it("allows patch_section", () => {
      expect(isWriteAllowed("work/action-items.md", "patch_section")).toBe(true);
    });

    it("blocks rewrite", () => {
      expect(isWriteAllowed("work/action-items.md", "rewrite")).toBe(false);
    });
  });

  describe("glacier/index.md", () => {
    it("blocks all modes", () => {
      expect(isWriteAllowed("glacier/index.md", "rewrite")).toBe(false);
      expect(isWriteAllowed("glacier/index.md", "append")).toBe(false);
      expect(isWriteAllowed("glacier/index.md", "patch_section")).toBe(false);
    });

    it("has blocked reason", () => {
      const rule = getWriteRule("glacier/index.md");
      expect(rule.blocked).toBeDefined();
      expect(rule.blocked).toContain("Auto-generated");
    });
  });

  describe("*/INDEX.md", () => {
    it("blocks all writes to any INDEX.md file", () => {
      expect(isWriteAllowed("threads/project-alpha/INDEX.md", "rewrite")).toBe(false);
      expect(isWriteAllowed("threads/project-alpha/INDEX.md", "append")).toBe(false);
      expect(isWriteAllowed("threads/project-alpha/INDEX.md", "patch_section")).toBe(false);
    });
  });

  describe("habits.md", () => {
    it("allows only patch_section", () => {
      expect(isWriteAllowed("personal/habits.md", "patch_section")).toBe(true);
      expect(isWriteAllowed("personal/habits.md", "rewrite")).toBe(false);
      expect(isWriteAllowed("personal/habits.md", "append")).toBe(false);
    });
  });

  describe("entities.md", () => {
    it("allows only patch_section", () => {
      expect(isWriteAllowed("work/entities.md", "patch_section")).toBe(true);
      expect(isWriteAllowed("work/entities.md", "rewrite")).toBe(false);
      expect(isWriteAllowed("work/entities.md", "append")).toBe(false);
    });
  });

  describe("health.md", () => {
    it("allows only patch_section", () => {
      expect(isWriteAllowed("personal/health.md", "patch_section")).toBe(true);
      expect(isWriteAllowed("personal/health.md", "rewrite")).toBe(false);
      expect(isWriteAllowed("personal/health.md", "append")).toBe(false);
    });
  });

  describe("cog-meta/patterns.md", () => {
    it("allows only patch_section", () => {
      expect(isWriteAllowed("cog-meta/patterns.md", "patch_section")).toBe(true);
      expect(isWriteAllowed("cog-meta/patterns.md", "rewrite")).toBe(false);
      expect(isWriteAllowed("cog-meta/patterns.md", "append")).toBe(false);
    });
  });

  describe("link-index.md", () => {
    it("blocks all modes", () => {
      expect(isWriteAllowed("link-index.md", "rewrite")).toBe(false);
      expect(isWriteAllowed("link-index.md", "append")).toBe(false);
      expect(isWriteAllowed("link-index.md", "patch_section")).toBe(false);
    });
  });

  describe("default behavior (unknown files)", () => {
    it("allows all modes for thread files", () => {
      const threadFile = "threads/project-alpha/current-state.md";
      expect(isWriteAllowed(threadFile, "rewrite")).toBe(true);
      expect(isWriteAllowed(threadFile, "append")).toBe(true);
      expect(isWriteAllowed(threadFile, "patch_section")).toBe(true);
    });

    it("allows all modes for new custom files", () => {
      const customFile = "personal/my-custom-notes.md";
      expect(isWriteAllowed(customFile, "rewrite")).toBe(true);
      expect(isWriteAllowed(customFile, "append")).toBe(true);
      expect(isWriteAllowed(customFile, "patch_section")).toBe(true);
    });
  });
});
