/**
 * Bootstrap script — initialize Majordomo's memory and data directory structure.
 * Run once before first use: bun packages/agent/scripts/bootstrap.ts
 */

import * as path from "node:path";
import * as fs from "node:fs/promises";

const PROJECT_ROOT = process.cwd();
const MEMORY_ROOT = path.join(PROJECT_ROOT, "memory");
const DATA_ROOT = path.join(PROJECT_ROOT, "data");

// ── Helpers ───────────────────────────────────────────────────────────────────

async function writeIfNotExists(filePath: string, content: string): Promise<{ created: boolean }> {
  const exists = await fs.access(filePath).then(() => true).catch(() => false);
  if (exists) return { created: false };
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, content, "utf-8");
  return { created: true };
}

function log(msg: string) { console.log(msg); }
function created(filePath: string) { log(`  ✓  ${path.relative(PROJECT_ROOT, filePath)}`); }
function skipped(filePath: string) { log(`  -  ${path.relative(PROJECT_ROOT, filePath)} (already exists)`); }

// ── Bootstrap ─────────────────────────────────────────────────────────────────

log("\n🏗  Majordomo Bootstrap\n");
log("Creating memory/ structure...\n");

// ── memory/domains.yml ────────────────────────────────────────────────────────

const domainsYml = `# Majordomo Domain Manifest — managed by domain-manager extension
# To add domains: ask Majordomo to create one (or use /domain-create)

domains:
  - id: general
    path: general
    type: general
    label: "General — fallback domain, cross-domain work, system tasks"
    triggers: []
    files: [hot-memory, action-items, observations]
    status: active
    created_at: ${new Date().toISOString().slice(0, 10)}

  - id: cog-meta
    path: cog-meta
    type: system
    label: "Majordomo self-knowledge and pipeline health"
    triggers: [cog, meta, evolve, memory, pipeline, architecture, self-improvement]
    files: [self-observations, patterns, improvements]
    status: active
    created_at: ${new Date().toISOString().slice(0, 10)}
`;

{ const f = path.join(MEMORY_ROOT, "domains.yml"); const r = await writeIfNotExists(f, domainsYml); r.created ? created(f) : skipped(f); }

// ── memory/hot-memory.md ──────────────────────────────────────────────────────

const hotMemory = `<!-- L0: cross-domain hot memory — what matters right now across all domains -->
# Hot Memory

*This file is always loaded. Keep it under 50 lines. Only put things here that are immediately relevant.*
`;

{ const f = path.join(MEMORY_ROOT, "hot-memory.md"); const r = await writeIfNotExists(f, hotMemory); r.created ? created(f) : skipped(f); }

// ── memory/link-index.md ──────────────────────────────────────────────────────

const linkIndex = `<!-- L0: memory link index — backlinks between files (auto-generated by /cog-housekeeping) -->
# Memory Link Index
<!-- Auto-generated by /cog-housekeeping. Do not edit manually. -->
<!-- Last updated: never -->

| Target | Linked from |
|--------|-------------|
`;

{ const f = path.join(MEMORY_ROOT, "link-index.md"); const r = await writeIfNotExists(f, linkIndex); r.created ? created(f) : skipped(f); }

// ── memory/cog-meta/ ──────────────────────────────────────────────────────────

const cogMetaFiles: Record<string, string> = {
  "patterns.md": `<!-- L0: universal interaction patterns — distilled rules applied every conversation -->
# Patterns

*Universal rules for how Majordomo should behave. Loaded every turn. Hard cap: 70 lines.*
*Domain-specific patterns go in their own domain's patterns.md file.*

## Memory
- Always read hot-memory before responding to any query
- L0 scan first when unsure which file to load — one call, many files, few tokens
- Write observations immediately — don't defer

## Communication
- Be direct. No filler phrases. Get to the point.
- Use structured output (bullet lists, headers) for anything with more than 3 parts
- When you've done something, state what you did and what's next
`,

  "self-observations.md": `<!-- L0: Majordomo self-observations — append-only log of what worked and didn't -->
# Self-Observations

*Append only. Format: - YYYY-MM-DD [tag]: observation*
*Max 50 entries before archiving to glacier.*

`,

  "improvements.md": `<!-- L0: Majordomo improvement ideas — wishlist and repair notes -->
# Improvements

## Wishlist

## In Progress

## Implemented
`,

  "reflect-cursor.md": `<!-- L0: reflect ingestion cursor — session path and last-processed timestamp for /cog-reflect -->
# Reflect Cursor

session_path: ${DATA_ROOT.replace(/\\/g, "/")}
last_processed: never
`,

  "scenario-calibration.md": `<!-- L0: scenario calibration — accuracy tracking for /scenario decisions -->
# Scenario Calibration

*Updated by /cog-reflect. Tracks how well scenario predictions matched reality.*
`,
};

for (const [filename, content] of Object.entries(cogMetaFiles)) {
  const f = path.join(MEMORY_ROOT, "cog-meta", filename);
  const r = await writeIfNotExists(f, content);
  r.created ? created(f) : skipped(f);
}

// ── memory/general/ ───────────────────────────────────────────────────────────

const generalFiles: Record<string, string> = {
  "hot-memory.md": `<!-- L0: general domain hot memory — active cross-domain state -->
# Hot Memory — General

*Cross-domain tasks, system state, and anything without a home domain.*
`,
  "action-items.md": `<!-- L0: general action items — open and completed tasks -->
# Action Items — General

`,
  "observations.md": `<!-- L0: general observations — append-only log of notable events -->
# Observations — General

`,
};

for (const [filename, content] of Object.entries(generalFiles)) {
  const f = path.join(MEMORY_ROOT, "general", filename);
  const r = await writeIfNotExists(f, content);
  r.created ? created(f) : skipped(f);
}

// ── data/ ─────────────────────────────────────────────────────────────────────

log("\nCreating data/ structure...\n");

await fs.mkdir(path.join(DATA_ROOT, "sessions", "general"), { recursive: true });
log(`  ✓  data/sessions/general/`);

await fs.mkdir(path.join(DATA_ROOT, "widgets"), { recursive: true });
log(`  ✓  data/widgets/`);

const telegramMap = `# Telegram topic → domain mapping
# Managed by domain-manager extension. NOT part of COG memory.
# Set supergroup_id and assign thread_ids when configuring Telegram.

telegram:
  bot_token_env: TELEGRAM_BOT_TOKEN
  supergroup_id: null

topics:
  general:
    thread_id: null
    created_at: ${new Date().toISOString().slice(0, 10)}
`;

{ const f = path.join(DATA_ROOT, "telegram-map.yaml"); const r = await writeIfNotExists(f, telegramMap); r.created ? created(f) : skipped(f); }

// ── Final ─────────────────────────────────────────────────────────────────────

log(`
✅  Bootstrap complete!

Next steps:
  1. Authenticate: run \`pi\` → /login → GitHub Copilot (uses your subscription, no API key)
     Or set ANTHROPIC_API_KEY in your environment for Claude.

  2. Start Majordomo:
     bun packages/agent/main.ts                    # general domain
     bun packages/agent/main.ts --domain personal  # personal domain (create it first)

  3. In Majordomo, create your domains:
     "Create a domain for my personal life"
     "Create a work domain for my job at Acme"

  4. Edit packages/agent/persona/majordomo.md to customize the persona.
`);
