/**
 * COG Memory Extension
 *
 * Implements the full COG L0 → L1 → L2 retrieval protocol as pi tools.
 * Injects the always-read memory tier into every system prompt turn.
 *
 * Tools registered:
 *   cog_l0_scan          — grep L0 headers across a domain directory
 *   cog_l1_scan          — extract section headers from a file
 *   cog_read             — read a memory file (L2), optionally a specific section
 *   cog_write            — write to a memory file with edit-pattern enforcement
 *   cog_append_observation — append a timestamped observation entry
 *   cog_update_action_item — add / complete / update an action item
 *   cog_glacier_search   — search the glacier index without opening files
 *   cog_wiki_follow      — resolve and read a [[wiki-link]]
 */

import * as path from "node:path";
import * as fs from "node:fs/promises";
import { StringEnum } from "@mariozechner/pi-ai";
import { type ExtensionAPI, type AgentToolResult, withFileMutationQueue } from "@mariozechner/pi-coding-agent";
import { Type } from "@sinclair/typebox";
import { createLogger } from "../../lib/logger.ts";

const logger = createLogger({ context: { component: "cog-memory" } });

// ── Types ─────────────────────────────────────────────────────────────────────

export interface CogMemoryOptions {
  memoryRoot: string;
  getDomain: () => string;  // Dynamic domain accessor
}

interface L0Entry {
  file: string;   // relative to memory root, e.g. "personal/action-items.md"
  summary: string;
}

// ── Per-file write mode rules ──────────────────────────────────────────────────

type WriteMode = "rewrite" | "append" | "patch_section";

interface WriteRule {
  allowed: WriteMode[];
  blocked?: string; // reason if all modes are blocked
}

const WRITE_RULES: Record<string, WriteRule> = {
  "hot-memory.md":                  { allowed: ["rewrite"] },
  "observations.md":                { allowed: ["append"] },
  "action-items.md":                { allowed: ["append", "patch_section"] },
  "entities.md":                    { allowed: ["patch_section"] },
  "calendar.md":                    { allowed: ["rewrite"] },
  "health.md":                      { allowed: ["patch_section"] },
  "habits.md":                      { allowed: ["patch_section"] },
  "home.md":                        { allowed: ["patch_section"] },
  "cog-meta/self-observations.md":  { allowed: ["append"] },
  "cog-meta/patterns.md":           { allowed: ["patch_section"] },
  "glacier/index.md":               { allowed: [], blocked: "Auto-generated by /cog-housekeeping — do not edit manually" },
  "link-index.md":                  { allowed: [], blocked: "Auto-generated by /cog-housekeeping — do not edit manually" },
};

// Thread files follow: Current State → rewrite, Timeline → append
// Any file ending in INDEX.md is blocked (auto-generated)
function getWriteRule(relPath: string): WriteRule {
  // Strip leading domain prefix for lookup, try exact filename match first
  const filename = path.basename(relPath);
  const relNorm = relPath.replace(/\\/g, "/");

  // Blocked patterns
  if (filename === "INDEX.md") {
    return { allowed: [], blocked: "Auto-generated by /cog-housekeeping — do not edit manually" };
  }
  if (relNorm === "glacier/index.md" || relNorm.endsWith("/glacier/index.md")) {
    return { allowed: [], blocked: "Auto-generated by /cog-housekeeping — do not edit manually" };
  }
  if (relNorm === "link-index.md") {
    return { allowed: [], blocked: "Auto-generated by /cog-housekeeping — do not edit manually" };
  }

  // Check exact relative path match (for cog-meta files)
  if (WRITE_RULES[relNorm]) return WRITE_RULES[relNorm];

  // Check basename match (works across domains, e.g. personal/observations.md)
  if (WRITE_RULES[filename]) return WRITE_RULES[filename];

  // Default: all modes allowed (thread files, new files, etc.)
  return { allowed: ["rewrite", "append", "patch_section"] };
}

// ── File helpers ───────────────────────────────────────────────────────────────

async function readMemoryFile(memoryRoot: string, relPath: string): Promise<string | null> {
  try {
    const content = await fs.readFile(path.join(memoryRoot, relPath), "utf-8");
    return content.trim() || null;
  } catch (err) {
    logger.debug("Skipping unreadable memory file", { relPath, error: err });
    return null;
  }
}

async function readMemoryFileIfToday(memoryRoot: string, relPath: string): Promise<string | null> {
  const fullPath = path.join(memoryRoot, relPath);
  try {
    const stat = await fs.stat(fullPath);
    const today = new Date().toDateString();
    if (new Date(stat.mtime).toDateString() !== today) return null;
    const content = await fs.readFile(fullPath, "utf-8");
    return content.trim() || null;
  } catch (err) {
    logger.debug("Skipping memory file (not found or not today)", { relPath, error: err });
    return null;
  }
}

async function scanL0(memoryRoot: string, domain: string): Promise<L0Entry[]> {
  const domainDir = path.join(memoryRoot, domain);
  const results: L0Entry[] = [];
  try {
    const entries = await fs.readdir(domainDir, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isFile() || !entry.name.endsWith(".md")) continue;
      const filePath = path.join(domainDir, entry.name);
      try {
        const content = await fs.readFile(filePath, "utf-8");
        const firstLine = content.split("\n")[0] ?? "";
        const m = firstLine.match(/<!--\s*L0:\s*(.+?)\s*-->/);
        if (m) {
          results.push({
            file: path.join(domain, entry.name).replace(/\\/g, "/"),
            summary: m[1],
          });
        }
      } catch (err) {
        logger.debug("Skipping unreadable L0 file", { file: path.join(domain, entry.name), error: err });
      }
    }
  } catch (err) {
    logger.debug("Domain directory does not exist yet", { domain, error: err });
  }
  return results;
}

function extractSectionHeaders(content: string): Array<{ level: number; heading: string; line: number }> {
  const headers: Array<{ level: number; heading: string; line: number }> = [];
  const lines = content.split("\n");
  for (let i = 0; i < lines.length; i++) {
    const m = lines[i].match(/^(#{1,6})\s+(.+)$/);
    if (m) headers.push({ level: m[1].length, heading: m[2].trim(), line: i + 1 });
  }
  return headers;
}

function extractSection(content: string, sectionHeading: string): string | null {
  const lines = content.split("\n");
  const headingPattern = new RegExp(`^(#{1,6})\\s+${sectionHeading.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\s*$`, "i");

  let start = -1;
  let level = 0;

  for (let i = 0; i < lines.length; i++) {
    const m = lines[i].match(headingPattern);
    if (m) {
      start = i;
      level = m[1].length;
      break;
    }
  }

  if (start === -1) return null;

  let end = lines.length;
  for (let i = start + 1; i < lines.length; i++) {
    const lm = lines[i].match(/^(#{1,6})\s/);
    if (lm && lm[1].length <= level) {
      end = i;
      break;
    }
  }

  return lines.slice(start, end).join("\n");
}

function patchSection(content: string, sectionHeading: string, newContent: string): string {
  const lines = content.split("\n");
  const headingPattern = new RegExp(`^(#{1,6})\\s+${sectionHeading.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\s*$`, "i");

  let start = -1;
  let level = 0;

  for (let i = 0; i < lines.length; i++) {
    const m = lines[i].match(headingPattern);
    if (m) {
      start = i;
      level = m[1].length;
      break;
    }
  }

  if (start === -1) {
    // Section not found — append it
    const heading = "#".repeat(level || 2) + " " + sectionHeading;
    return content.trimEnd() + "\n\n" + heading + "\n\n" + newContent.trimEnd() + "\n";
  }

  let end = lines.length;
  for (let i = start + 1; i < lines.length; i++) {
    const lm = lines[i].match(/^(#{1,6})\s/);
    if (lm && lm[1].length <= level) {
      end = i;
      break;
    }
  }

  const before = lines.slice(0, start + 1).join("\n");
  const after = lines.slice(end).join("\n");
  const separator = after.trimStart() ? "\n\n" : "\n";
  return before + "\n\n" + newContent.trimEnd() + separator + after;
}

function ensureL0Header(content: string, summary: string): string {
  const l0Pattern = /^<!--\s*L0:.*?-->/;
  const firstLine = content.split("\n")[0] ?? "";
  if (l0Pattern.test(firstLine)) return content; // already has one
  return `<!-- L0: ${summary} -->\n${content}`;
}

function today(): string {
  return new Date().toISOString().slice(0, 10);
}

// ── Parse glacier index table ─────────────────────────────────────────────────

interface GlacierEntry {
  file: string;
  domain: string;
  type: string;
  tags: string[];
  dateRange: string;
  entries: string;
  summary: string;
}

function parseGlacierIndex(content: string): GlacierEntry[] {
  const entries: GlacierEntry[] = [];
  const lines = content.split("\n");
  let inTable = false;
  for (const line of lines) {
    if (line.startsWith("| File |")) { inTable = true; continue; }
    if (inTable && line.startsWith("|---")) continue;
    if (!inTable || !line.startsWith("|")) continue;
    const cols = line.split("|").map(s => s.trim()).filter(Boolean);
    if (cols.length >= 7) {
      entries.push({
        file: cols[0],
        domain: cols[1],
        type: cols[2],
        tags: cols[3].split(",").map(t => t.trim()),
        dateRange: cols[4],
        entries: cols[5],
        summary: cols[6],
      });
    }
  }
  return entries;
}

// ── Extension factory ─────────────────────────────────────────────────────────

export function cogMemoryExtensionFactory(opts: CogMemoryOptions) {
  return (pi: ExtensionAPI) => {
    const { memoryRoot, getDomain } = opts;

    // ── before_agent_start: inject always-read memory tier ────────────────────

    pi.on("before_agent_start", async (event) => {
      const sections: string[] = [];
      const activeDomain = getDomain();  // Read current domain dynamically

      // 1. Cross-domain hot memory
      const globalHot = await readMemoryFile(memoryRoot, "hot-memory.md");
      if (globalHot) {
        sections.push("### Cross-Domain Hot Memory\n\n" + globalHot);
      }

      // 2. Universal patterns
      const patterns = await readMemoryFile(memoryRoot, "cog-meta/patterns.md");
      if (patterns) {
        sections.push("### Universal Interaction Patterns\n\n" + patterns);
      }

      // 3. Domain hot memory (walk up for nested domains, e.g. work/acme)
      const parts = activeDomain.split("/");
      for (let i = 1; i <= parts.length; i++) {
        const partial = parts.slice(0, i).join("/");
        const domHot = await readMemoryFile(memoryRoot, `${partial}/hot-memory.md`);
        if (domHot) {
          const label = i < parts.length ? `Domain Hot Memory (${partial})` : `Domain Hot Memory`;
          sections.push(`### ${label}\n\n` + domHot);
        }
      }

      // 4. L0 scan of active domain
      const l0Entries = await scanL0(memoryRoot, activeDomain);
      if (l0Entries.length > 0) {
        const l0Text = l0Entries.map(e => `- **${e.file}**: ${e.summary}`).join("\n");
        sections.push(`### Domain File Index (${activeDomain})\n\n${l0Text}`);
      }

      // 5. Today's foresight nudge (if written today)
      const nudge = await readMemoryFileIfToday(memoryRoot, "cog-meta/foresight-nudge.md");
      if (nudge) {
        sections.push("### Today's Strategic Nudge\n\n" + nudge);
      }

      if (sections.length === 0) return undefined;

      const cogBlock =
        "\n\n---\n\n## Working Memory (Active Domain: " + activeDomain + ")\n\n" +
        sections.join("\n\n---\n\n") +
        "\n\n---";

      return { systemPrompt: event.systemPrompt + cogBlock };
    });

    // ── cog_l0_scan ──────────────────────────────────────────────────────────

    pi.registerTool({
      name: "cog_l0_scan",
      label: "COG L0 Scan",
      description:
        "Scan a domain directory for L0 header summaries. Use this first when you're unsure which memory file contains relevant information. Returns one line per file: filename and its L0 summary.",
      promptSnippet: "Scan COG memory domain for file summaries (L0 tier — first step of retrieval)",
      parameters: Type.Object({
        domain: Type.Optional(
          Type.String({ description: `Domain to scan. Defaults to active domain. Use nested paths like 'work/acme'.` })
        ),
      }),
      async execute(_id, params): Promise<AgentToolResult<Record<string, unknown>>> {
        const targetDomain = params.domain ?? getDomain();
        const entries = await scanL0(memoryRoot, targetDomain);
        if (entries.length === 0) {
          return {
            content: [{ type: "text", text: `No L0-indexed files found in domain '${targetDomain}'. The domain may not exist yet or no files have L0 headers.` }],
            details: { domain: targetDomain, entries: [] },
          };
        }
        const text = entries.map(e => `${e.file}: ${e.summary}`).join("\n");
        return {
          content: [{ type: "text", text }],
          details: { domain: targetDomain, entries },
        };
      },
    });

    // ── cog_l1_scan ──────────────────────────────────────────────────────────

    pi.registerTool({
      name: "cog_l1_scan",
      label: "COG L1 Scan",
      description:
        "Extract section headers (## and ###) from a memory file. Use before reading files that are longer than ~80 lines to decide which section you need. Paths are relative to the memory/ root.",
      promptSnippet: "Scan section headers of a COG memory file (L1 tier — use before full read for large files)",
      parameters: Type.Object({
        file_path: Type.String({ description: "Path relative to memory/ root, e.g. 'personal/health.md'" }),
      }),
      async execute(_id, params): Promise<AgentToolResult<Record<string, unknown>>> {
        const content = await readMemoryFile(memoryRoot, params.file_path);
        if (!content) {
          return {
            content: [{ type: "text", text: `File not found: memory/${params.file_path}` }],
            details: { file_path: params.file_path, headers: [] },
          };
        }
        const headers = extractSectionHeaders(content);
        if (headers.length === 0) {
          const lines = content.split("\n").length;
          return {
            content: [{ type: "text", text: `No section headers found in memory/${params.file_path} (${lines} lines). Use cog_read to read the full file.` }],
            details: { file_path: params.file_path, headers: [], lineCount: lines },
          };
        }
        const text = headers.map(h => `L${"#".repeat(h.level)} ${h.heading} (line ${h.line})`).join("\n");
        return {
          content: [{ type: "text", text }],
          details: { file_path: params.file_path, headers },
        };
      },
    });

    // ── cog_read ─────────────────────────────────────────────────────────────

    pi.registerTool({
      name: "cog_read",
      label: "COG Read",
      description:
        "Read a memory file (L2 full read), optionally just a specific section by heading text. Paths relative to memory/ root. For files >80 lines, consider cog_l1_scan first to find the right section.",
      promptSnippet: "Read a COG memory file or section (L2 tier — full content retrieval)",
      parameters: Type.Object({
        file_path: Type.String({ description: "Path relative to memory/ root, e.g. 'personal/entities.md'" }),
        section: Type.Optional(Type.String({ description: "Section heading text to read (reads full file if omitted)" })),
      }),
      async execute(_id, params): Promise<AgentToolResult<Record<string, unknown>>> {
        const content = await readMemoryFile(memoryRoot, params.file_path);
        if (!content) {
          return {
            content: [{ type: "text", text: `File not found: memory/${params.file_path}` }],
            details: { file_path: params.file_path, found: false },
          };
        }

        if (params.section) {
          const sectionContent = extractSection(content, params.section);
          if (!sectionContent) {
            const headers = extractSectionHeaders(content).map(h => h.heading);
            return {
              content: [{ type: "text", text: `Section '${params.section}' not found. Available sections: ${headers.join(", ") || "(none)"}` }],
              details: { file_path: params.file_path, section: params.section, found: false },
            };
          }
          return {
            content: [{ type: "text", text: sectionContent }],
            details: { file_path: params.file_path, section: params.section, found: true },
          };
        }

        return {
          content: [{ type: "text", text: content }],
          details: { file_path: params.file_path, lineCount: content.split("\n").length },
        };
      },
    });

    // ── cog_write ────────────────────────────────────────────────────────────

    pi.registerTool({
      name: "cog_write",
      label: "COG Write",
      description: [
        "Write to a COG memory file. Enforces per-file edit patterns:",
        "- hot-memory.md: rewrite only",
        "- observations.md, self-observations.md: append only",
        "- action-items.md: append (new tasks) or patch_section (update existing)",
        "- entities.md: patch_section only (3-line max per ### entry)",
        "- calendar.md: rewrite only",
        "- health.md, habits.md: patch_section only",
        "- cog-meta/patterns.md: patch_section only (70-line hard cap)",
        "- glacier/index.md, link-index.md, */INDEX.md: BLOCKED (auto-generated)",
        "- Thread files and new files: all modes allowed",
        "Always include a <!-- L0: summary --> header as the first line.",
      ].join(" "),
      promptSnippet: "Write to a COG memory file with edit-pattern enforcement",
      parameters: Type.Object({
        file_path: Type.String({ description: "Path relative to memory/ root, e.g. 'personal/hot-memory.md'" }),
        content: Type.String({ description: "Content to write" }),
        mode: StringEnum(["rewrite", "append", "patch_section"] as const, {
          description: "Write mode. Must match the allowed modes for this file.",
        }),
        section: Type.Optional(Type.String({
          description: "Section heading for patch_section mode. Created if not found.",
        })),
      }),
      async execute(_id, params): Promise<AgentToolResult<Record<string, unknown>>> {
        const relPath = params.file_path.replace(/\\/g, "/");
        const rule = getWriteRule(relPath);

        // Check if blocked
        if (rule.allowed.length === 0) {
          return {
            content: [{ type: "text", text: `❌  Cannot write to memory/${relPath}: ${rule.blocked}` }],
            details: { file_path: relPath, blocked: true },
          };
        }

        // Check mode is allowed
        if (!rule.allowed.includes(params.mode as WriteMode)) {
          return {
            content: [{ type: "text", text: `❌  Mode '${params.mode}' not allowed for memory/${relPath}. Allowed: ${rule.allowed.join(", ")}` }],
            details: { file_path: relPath, mode: params.mode, allowedModes: rule.allowed },
          };
        }

        // patch_section requires a section
        if (params.mode === "patch_section" && !params.section) {
          return {
            content: [{ type: "text", text: "❌  patch_section mode requires a 'section' parameter (the ## heading text)" }],
            details: { file_path: relPath },
          };
        }

        const fullPath = path.join(memoryRoot, relPath);
        await fs.mkdir(path.dirname(fullPath), { recursive: true });

        return withFileMutationQueue(fullPath, async () => {
          let newContent: string;

          if (params.mode === "rewrite") {
            // Ensure L0 header is present
            const firstLine = params.content.split("\n")[0] ?? "";
            if (/^<!--\s*L0:/.test(firstLine)) {
              newContent = params.content;
            } else {
              // Warn if no L0 header on rewrite — caller should add one
              newContent = params.content;
            }
          } else if (params.mode === "append") {
            const existing = await readMemoryFile(memoryRoot, relPath) ?? "";
            newContent = existing ? existing + "\n" + params.content : params.content;
          } else {
            // patch_section
            const existing = await readMemoryFile(memoryRoot, relPath) ?? "";
            newContent = patchSection(existing, params.section!, params.content);
          }

          await fs.writeFile(fullPath, newContent.trimEnd() + "\n", "utf-8");

          // Special cap enforcement for patterns.md
          if (relPath.endsWith("patterns.md")) {
            const written = await fs.readFile(fullPath, "utf-8");
            const lines = written.split("\n").length;
            if (lines > 75) {
              return {
                content: [{ type: "text", text: `⚠️  Written to memory/${relPath}. WARNING: file is ${lines} lines — approaching the 70-line hard cap. Consider compressing or moving domain-specific patterns to a satellite file.` }],
                details: { file_path: relPath, mode: params.mode, lineCount: lines },
              };
            }
          }

          return {
            content: [{ type: "text", text: `✓  Written to memory/${relPath} (${params.mode})` }],
            details: { file_path: relPath, mode: params.mode },
          };
        });
      },
    });

    // ── cog_append_observation ───────────────────────────────────────────────

    pi.registerTool({
      name: "cog_append_observation",
      label: "COG Append Observation",
      description:
        "Append a timestamped observation to a domain's observations.md file. Format: '- YYYY-MM-DD [tag1, tag2]: text'. Valid tags: health, habits, family, milestone, work, insight, regression, philosophy, mental-health. Creates the file if needed.",
      promptSnippet: "Append a timestamped observation to COG memory (append-only)",
      parameters: Type.Object({
        domain: Type.String({ description: "Domain to write to. Use active domain or specify another." }),
        text: Type.String({ description: "Observation text — what happened or was learned" }),
        tags: Type.Array(Type.String(), {
          description: "Classification tags. First tag is primary. Valid: health, habits, family, milestone, work, insight, regression, philosophy, mental-health",
        }),
      }),
      async execute(_id, params): Promise<AgentToolResult<Record<string, unknown>>> {
        const tagStr = params.tags.length > 0 ? `[${params.tags.join(", ")}]` : "";
        const entry = `- ${today()}${tagStr ? " " + tagStr : ""}: ${params.text}`;
        const filePath = path.join(memoryRoot, params.domain, "observations.md");

        await fs.mkdir(path.dirname(filePath), { recursive: true });

        return withFileMutationQueue(filePath, async () => {
          let existing = "";
          try { existing = await fs.readFile(filePath, "utf-8"); } catch (err) {
            logger.debug("New observations file, creating", { filePath, error: err });
          }

          if (!existing) {
            const l0 = `<!-- L0: ${params.domain} observations — append-only timestamped events -->`;
            existing = `${l0}\n# Observations\n`;
          }

          const updated = existing.trimEnd() + "\n" + entry + "\n";
          await fs.writeFile(filePath, updated, "utf-8");

          return {
            content: [{ type: "text", text: `✓  Observation appended to ${params.domain}/observations.md` }],
            details: { domain: params.domain, entry },
          };
        });
      },
    });

    // ── cog_update_action_item ───────────────────────────────────────────────

    pi.registerTool({
      name: "cog_update_action_item",
      label: "COG Action Item",
      description: [
        "Add, complete, or update an action item in a domain's action-items.md.",
        "Add format: '- [ ] task | due:YYYY-MM-DD | pri:critical/high/med/low | domain:tag | added:YYYY-MM-DD'",
        "Complete: marks '- [ ] ...' as '- [x] task (done YYYY-MM-DD)'",
        "Fields after task text are optional — include what's relevant.",
      ].join(" "),
      promptSnippet: "Add, complete, or update a COG action item",
      parameters: Type.Object({
        domain: Type.String({ description: "Domain for the action item" }),
        action: StringEnum(["add", "complete", "update"] as const),
        task: Type.String({ description: "Task text (for add/update) or matching text to find (for complete)" }),
        due: Type.Optional(Type.String({ description: "Due date YYYY-MM-DD" })),
        priority: Type.Optional(StringEnum(["critical", "high", "med", "low"] as const)),
        domain_tag: Type.Optional(Type.String({ description: "Domain tag for categorization" })),
        replacement_task: Type.Optional(Type.String({ description: "New task text (for update action)" })),
      }),
      async execute(_id, params): Promise<AgentToolResult<Record<string, unknown>>> {
        const filePath = path.join(memoryRoot, params.domain, "action-items.md");
        await fs.mkdir(path.dirname(filePath), { recursive: true });

        return withFileMutationQueue(filePath, async () => {
          let content = "";
          try { content = await fs.readFile(filePath, "utf-8"); } catch (err) {
            logger.debug("New action-items file, creating", { filePath, error: err });
          }

          if (!content) {
            const l0 = `<!-- L0: ${params.domain} action items — open and completed tasks -->`;
            content = `${l0}\n# Action Items\n`;
          }

          if (params.action === "add") {
            const parts = [`- [ ] ${params.task}`];
            if (params.due) parts.push(`due:${params.due}`);
            if (params.priority) parts.push(`pri:${params.priority}`);
            if (params.domain_tag) parts.push(`domain:${params.domain_tag}`);
            parts.push(`added:${today()}`);
            const entry = parts.join(" | ");
            const updated = content.trimEnd() + "\n" + entry + "\n";
            await fs.writeFile(filePath, updated, "utf-8");
            return {
              content: [{ type: "text", text: `✓  Action item added to ${params.domain}/action-items.md` }],
              details: { domain: params.domain, action: "add", entry },
            };
          }

          if (params.action === "complete") {
            const escapedTask = params.task.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
            const pattern = new RegExp(`^(- \\[[ ]\\] .{0,20}${escapedTask}.*)$`, "m");
            const match = content.match(pattern);
            if (!match) {
              return {
                content: [{ type: "text", text: `❌  No open task matching '${params.task}' found in ${params.domain}/action-items.md` }],
                details: { domain: params.domain, action: "complete", found: false },
              };
            }
            // Extract just the task text (before first |)
            const taskText = match[1].replace(/^- \[ \] /, "").split(" | ")[0];
            const updated = content.replace(match[1], `- [x] ${taskText} (done ${today()})`);
            await fs.writeFile(filePath, updated, "utf-8");
            return {
              content: [{ type: "text", text: `✓  Task marked complete in ${params.domain}/action-items.md` }],
              details: { domain: params.domain, action: "complete", task: taskText },
            };
          }

          if (params.action === "update") {
            if (!params.replacement_task) {
              return {
                content: [{ type: "text", text: "❌  update action requires 'replacement_task'" }],
                details: { domain: params.domain, action: "update" },
              };
            }
            const escapedTask = params.task.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
            const pattern = new RegExp(`^(- \\[[ x]\\] .{0,20}${escapedTask}.*)$`, "m");
            if (!content.match(pattern)) {
              return {
                content: [{ type: "text", text: `❌  No task matching '${params.task}' found in ${params.domain}/action-items.md` }],
                details: { domain: params.domain, action: "update", found: false },
              };
            }
            const updated = content.replace(pattern, `- [ ] ${params.replacement_task}`);
            await fs.writeFile(filePath, updated, "utf-8");
            return {
              content: [{ type: "text", text: `✓  Task updated in ${params.domain}/action-items.md` }],
              details: { domain: params.domain, action: "update" },
            };
          }

          return {
            content: [{ type: "text", text: "❌  Unknown action" }],
            details: {},
          };
        });
      },
    });

    // ── cog_glacier_search ───────────────────────────────────────────────────

    pi.registerTool({
      name: "cog_glacier_search",
      label: "COG Glacier Search",
      description:
        "Search the glacier index (memory/glacier/index.md) for archived files matching domain, tags, or date range. Does NOT open the glacier files — returns a list of matching files you can then open with cog_read.",
      promptSnippet: "Search COG glacier index for archived memory files",
      parameters: Type.Object({
        domain: Type.Optional(Type.String({ description: "Filter by domain (e.g. 'personal', 'work/acme')" })),
        tags: Type.Optional(Type.Array(Type.String(), { description: "Filter by tags (any match)" })),
        type: Type.Optional(Type.String({ description: "Filter by type: observations, action-items-done, entities-inactive, etc." })),
      }),
      async execute(_id, params): Promise<AgentToolResult<Record<string, unknown>>> {
        const indexContent = await readMemoryFile(memoryRoot, "glacier/index.md");
        if (!indexContent) {
          return {
            content: [{ type: "text", text: "Glacier index not found (memory/glacier/index.md). Run /cog-housekeeping to generate it." }],
            details: { entries: [] },
          };
        }

        let entries = parseGlacierIndex(indexContent);

        if (params.domain) {
          entries = entries.filter(e => e.domain === params.domain || e.domain.startsWith(params.domain + "/"));
        }
        if (params.type) {
          entries = entries.filter(e => e.type === params.type);
        }
        if (params.tags && params.tags.length > 0) {
          entries = entries.filter(e => params.tags!.some(t => e.tags.includes(t)));
        }

        if (entries.length === 0) {
          return {
            content: [{ type: "text", text: "No glacier files match the given filters." }],
            details: { entries: [] },
          };
        }

        const text = entries.map(e =>
          `${e.file} | domain:${e.domain} | type:${e.type} | tags:${e.tags.join(",")} | ${e.dateRange} | ${e.entries} entries — ${e.summary}`
        ).join("\n");

        return {
          content: [{ type: "text", text }],
          details: { entries },
        };
      },
    });

    // ── cog_wiki_follow ──────────────────────────────────────────────────────

    pi.registerTool({
      name: "cog_wiki_follow",
      label: "COG Wiki Follow",
      description:
        "Resolve and read a [[wiki-link]]. Format: [[domain/filename]] or [[domain/filename#Section]]. Automatically applies L1 scan for files >80 lines unless a specific section is requested.",
      promptSnippet: "Follow a [[wiki-link]] to a COG memory file or section",
      parameters: Type.Object({
        link: Type.String({ description: "Wiki-link text, e.g. '[[personal/health]]' or '[[work/acme/entities#Jane]]'" }),
      }),
      async execute(_id, params): Promise<AgentToolResult<Record<string, unknown>>> {
        // Parse [[domain/filename#Section]] or [[domain/filename]]
        const cleaned = params.link.replace(/^\[\[|\]\]$/g, "").trim();
        const [fileRef, section] = cleaned.split("#");
        const filePath = fileRef.endsWith(".md") ? fileRef : fileRef + ".md";

        const content = await readMemoryFile(memoryRoot, filePath);
        if (!content) {
          return {
            content: [{ type: "text", text: `Wiki-link target not found: memory/${filePath}` }],
            details: { link: params.link, found: false },
          };
        }

        if (section) {
          const sectionContent = extractSection(content, section);
          if (!sectionContent) {
            const headers = extractSectionHeaders(content).map(h => h.heading);
            return {
              content: [{ type: "text", text: `Section '${section}' not found in memory/${filePath}. Available: ${headers.join(", ") || "(none)"}` }],
              details: { link: params.link, found: false },
            };
          }
          return {
            content: [{ type: "text", text: sectionContent }],
            details: { link: params.link, file: filePath, section, found: true },
          };
        }

        // For large files without a specific section, show L1 headers first
        const lineCount = content.split("\n").length;
        if (lineCount > 80) {
          const headers = extractSectionHeaders(content);
          if (headers.length > 0) {
            const headerText = headers.map(h => `${"  ".repeat(h.level - 1)}${"#".repeat(h.level)} ${h.heading} (line ${h.line})`).join("\n");
            return {
              content: [{
                type: "text",
                text: `memory/${filePath} is ${lineCount} lines. Section headers:\n\n${headerText}\n\nUse cog_read with a section name to read a specific part, or cog_read without section for the full file.`,
              }],
              details: { link: params.link, file: filePath, lineCount, headers, needsL2: true },
            };
          }
        }

        return {
          content: [{ type: "text", text: content }],
          details: { link: params.link, file: filePath, lineCount, found: true },
        };
      },
    });
  };
}

// ── Default export for standalone pi extension loading ────────────────────────

export default function (pi: ExtensionAPI) {
  const memoryRoot = process.env.MAJORDOMO_MEMORY_ROOT ?? path.join(process.cwd(), "memory");
  const getDomain = () => process.env.MAJORDOMO_DOMAIN ?? "general";
  cogMemoryExtensionFactory({ memoryRoot, getDomain })(pi);
}
